# Generated by Django 5.2.3 on 2025-07-31 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authx', '0003_user_is_online_user_last_logout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_logout',
        ),
    ]
