# Generated by Django 5.2.3 on 2025-08-03 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authx', '0004_remove_user_last_logout'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_logout',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
