# Generated by Django 5.2.3 on 2025-08-04 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authx', '0005_user_last_logout'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='module',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='permission',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='permission',
            name='type',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
