# Generated by Django 5.2.3 on 2025-08-09 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authx', '0010_remove_customer_organization_customer_department_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='totalAmount',
            new_name='timesMarked',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='deviceName',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='organization',
        ),
    ]
