# Generated by Django 5.2.3 on 2025-08-09 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authx', '0011_rename_totalamount_contract_timesmarked_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['name'], 'permissions': [('can_share_role', 'Can share role')], 'verbose_name': 'Role', 'verbose_name_plural': 'Roles'},
        ),
    ]
