# Generated by Django 5.2.3 on 2025-08-11 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authx', '0012_alter_role_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permission',
            options={'ordering': ['codename'], 'permissions': [('can_share_role', 'Can share role')], 'verbose_name': 'Permission', 'verbose_name_plural': 'Permissions'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['name'], 'verbose_name': 'Role', 'verbose_name_plural': 'Roles'},
        ),
    ]
