# Generated by Django 5.2.3 on 2025-08-11 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authx', '0013_alter_permission_options_alter_role_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permission',
            options={'ordering': ['codename'], 'permissions': [('can_deliver_pizzas', 'Can deliver pizzas')], 'verbose_name': 'Permission', 'verbose_name_plural': 'Permissions'},
        ),
    ]
