# Generated by Django 5.2.3 on 2025-08-11 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authx', '0014_alter_permission_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permission',
            options={'ordering': ['codename'], 'permissions': [('can_share_role', 'Can share role')], 'verbose_name': 'Permission', 'verbose_name_plural': 'Permissions'},
        ),
    ]
