# Generated by Django 5.2.3 on 2025-08-11 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authx', '0015_alter_permission_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='department',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='group',
        ),
        migrations.AddField(
            model_name='customer',
            name='organization',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
