# Generated by Django 5.2.3 on 2025-08-13 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authx', '0016_remove_customer_department_remove_customer_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='users', to='authx.group'),
        ),
    ]
